apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ca2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: gateway
          image: gateway:local
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          env:
            - name: CHECKOUT_URL
              value: http://checkout:5001/checkout
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: service-auth-secret
                  key: SERVICE_KEY
